#!/usr/bin/env node
/*
 * Writes site/sw.js — the service worker that makes the app work with no
 * network at all.
 *
 *   node tools/build-sw.mjs
 *
 * The worker precaches every file under site/, so the list and the cache name
 * have to match what is actually there. Both are generated here: the cache name
 * is a hash of the files' contents, so a deploy that changes anything gets a
 * fresh cache and a deploy that changes nothing does not. Run this after
 * touching anything in site/ — the Pages workflow runs it before publishing, so
 * what ships is always in step even if the committed copy drifts.
 */
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = join(ROOT, "site");

/* Generated, or served only to crawlers and tooling. The app never fetches any
   of these, so caching them would only cost space. The extension rule covers the
   licence files that ship beside the fonts and the vendored libraries. */
const SKIP = new Set(["sw.js", ".nojekyll", "robots.txt", "README.md", "data/README.md"]);
const SKIP_EXT = [".txt", ".md"];

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = (await walk(SITE))
  .map(f => relative(SITE, f).split(sep).join("/"))
  .filter(f => !SKIP.has(f) && !SKIP_EXT.some(ext => f.endsWith(ext)))
  .sort();

const hash = createHash("sha256");
for (const f of files) {
  hash.update(f);
  hash.update(await readFile(join(SITE, f)));
}
const version = hash.digest("hex").slice(0, 12);

/* "./" is the start_url; the rest are the assets the page pulls in. Relative
   URLs resolve against the worker's own location, so the app works just as well
   under a GitHub Pages project path as at a domain root. */
const precache = ["./", ...files.map(f => `./${f}`)];

const sw = `/* Generated by tools/build-sw.mjs — do not edit by hand.
   Precaches the whole app so it opens with no network: on a plane, on a phone
   with roaming off, anywhere. ${files.length} files, version from their contents. */
const VERSION = ${JSON.stringify(version)};
const CACHE = \`japan-travel-\${VERSION}\`;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

/* A new version takes over as soon as it has cached everything it needs, and
   the page reloads onto it (js/app.js). Each version's files are cached
   together, so what is on screen is never half old, half new. Offline there is
   no update check, and the last complete version keeps working. */
self.addEventListener("install", event => {
  event.waitUntil(
    caches
      .open(CACHE)
      /* cache: "reload" goes past the browser's HTTP cache. GitHub Pages sends
         max-age=600, so without it a version deployed in the last ten minutes
         would be precached with the previous version's files — and then kept. */
      .then(cache => cache.addAll(PRECACHE.map(url => new Request(url, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches
      .keys()
      .then(keys =>
        Promise.all(
          keys.filter(k => k.startsWith("japan-travel-") && k !== CACHE).map(k => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", event => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  /* A navigation may carry ?date=..., which must not miss the cached page. */
  if (request.mode === "navigate") {
    event.respondWith(
      caches.match("./", { ignoreSearch: true }).then(hit => hit || fetch(request))
    );
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then(hit => hit || fetch(request))
  );
});
`;

await writeFile(join(SITE, "sw.js"), sw);
console.log(`→ site/sw.js  (${files.length} files, version ${version})`);
