#!/usr/bin/env node
/*
 * Re-creates everything under site/vendor, site/fonts and site/data from npm.
 *
 * The design prototype pulled d3, topojson-client and the world-atlas geometry
 * from a CDN at runtime. This site ships them locally instead, so the itinerary
 * opens on a plane or on foreign roaming. Run this script to refresh or audit
 * those files:
 *
 *   node tools/vendor-assets.mjs
 *
 * It only needs `npm pack` (the public registry) and `tar`.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = join(ROOT, "site");

/* topojson-client is a build-time dependency only: the country geometry is
   converted to GeoJSON here so the browser never has to decode TopoJSON. */
/* d3-array is d3-geo's only runtime dependency, and its UMD build already
   bundles internmap, so these two files are the whole map engine. */
const PACKAGES = {
  "d3-geo": "3.1.1",
  "d3-array": "3.2.4",
  "topojson-client": "3.1.0",
  "world-atlas": "2.0.2",
  "@fontsource/heebo": "5.3.0",
  "@fontsource/caprasimo": "5.3.0",
};

/* Heebo carries the Hebrew body and UI text; Caprasimo is the Latin display
   face. Only the weights the stylesheets actually ask for are shipped. */
const HEEBO_WEIGHTS = [400, 500, 700];
const HEEBO_SUBSETS = ["hebrew", "latin"];
const CAPRASIMO_SUBSETS = ["latin", "latin-ext"];

/* 110m Natural Earth vertices are already far coarser than 3 decimal places
   (~0.2px at the Japan view's zoom), so rounding there is lossless on screen
   and trims about a fifth off the file. */
const COORD_DECIMALS = 3;

const work = mkdtempSync(join(tmpdir(), "vendor-assets-"));
const dirOf = name => join(work, name.replace("@fontsource/", "fontsource-"));

try {
  console.log("→ fetching packages from npm");
  const specs = Object.entries(PACKAGES).map(([n, v]) => `${n}@${v}`);
  execFileSync("npm", ["pack", ...specs], { cwd: work, stdio: ["ignore", "ignore", "inherit"] });

  for (const [name, version] of Object.entries(PACKAGES)) {
    const tgz = `${name.replace("@fontsource/", "fontsource-")}-${version}.tgz`;
    execFileSync("tar", ["xzf", tgz], { cwd: work });
    execFileSync("mv", ["package", dirOf(name)], { cwd: work });
  }

  for (const dir of ["vendor", "fonts", "data"]) mkdirSync(join(SITE, dir), { recursive: true });

  console.log("→ vendor/ — d3-geo and its dependencies");
  for (const name of ["d3-geo", "d3-array"]) {
    copyFileSync(join(dirOf(name), "dist", `${name}.min.js`), join(SITE, "vendor", `${name}.min.js`));
    copyFileSync(join(dirOf(name), "LICENSE"), join(SITE, "vendor", `LICENSE-${name}.txt`));
  }

  console.log("→ fonts/ — Heebo and Caprasimo woff2 subsets");
  for (const w of HEEBO_WEIGHTS) {
    for (const s of HEEBO_SUBSETS) {
      const f = `heebo-${s}-${w}-normal.woff2`;
      copyFileSync(join(dirOf("@fontsource/heebo"), "files", f), join(SITE, "fonts", f));
    }
  }
  for (const s of CAPRASIMO_SUBSETS) {
    const f = `caprasimo-${s}-400-normal.woff2`;
    copyFileSync(join(dirOf("@fontsource/caprasimo"), "files", f), join(SITE, "fonts", f));
  }
  copyFileSync(join(dirOf("@fontsource/heebo"), "LICENSE"), join(SITE, "fonts", "LICENSE-Heebo.txt"));
  copyFileSync(join(dirOf("@fontsource/caprasimo"), "LICENSE"), join(SITE, "fonts", "LICENSE-Caprasimo.txt"));

  console.log("→ data/ — countries-110m TopoJSON → GeoJSON");
  copyFileSync(join(dirOf("world-atlas"), "LICENSE"), join(SITE, "data", "LICENSE-world-atlas.txt"));
  const topojson = await import(join(dirOf("topojson-client"), "dist", "topojson-client.js"));
  const topo = JSON.parse(readFileSync(join(dirOf("world-atlas"), "countries-110m.json"), "utf8"));
  const collection = topojson.feature(topo, topo.objects.countries);

  const f = 10 ** COORD_DECIMALS;
  const round = n => Math.round(n * f) / f;
  const walk = c => (Array.isArray(c[0]) ? c.map(walk) : [round(c[0]), round(c[1])]);

  /* Country names and ids are dropped — the map only fills and strokes the
     outlines, and every place the page names comes from the itinerary data. */
  const geo = {
    type: "FeatureCollection",
    features: collection.features.map(feature => ({
      type: "Feature",
      geometry: { type: feature.geometry.type, coordinates: walk(feature.geometry.coordinates) },
    })),
  };

  /* Written as a script that assigns a global rather than a .json fetched at
     runtime, so index.html also works when opened straight off the filesystem
     (file:// blocks fetch and ES modules). */
  const banner =
    "/* Country outlines, Natural Earth 1:110m via world-atlas@2.0.2 (ISC).\n" +
    "   Generated by tools/vendor-assets.mjs — do not edit by hand. */\n";
  writeFileSync(
    join(SITE, "data", "countries.js"),
    `${banner}window.WORLD_LAND = ${JSON.stringify(geo)};\n`
  );
  writeFileSync(
    join(SITE, "data", "README.md"),
    "# data/\n\n" +
      "`countries.js` holds country outlines from [world-atlas](https://github.com/topojson/world-atlas)\n" +
      "2.0.2 (ISC), derived from [Natural Earth](https://www.naturalearthdata.com) 1:110m, which is in\n" +
      "the public domain. Regenerate it with `node tools/vendor-assets.mjs`.\n"
  );

  console.log("done.");
} finally {
  rmSync(work, { recursive: true, force: true });
}
